/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactFormImport } from './routes/contact-form'
import { Route as IndexImport } from './routes/index'
import { Route as ItemsItemIdImport } from './routes/items/$itemId'

// Create/Update Routes

const ContactFormRoute = ContactFormImport.update({
  id: '/contact-form',
  path: '/contact-form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ItemsItemIdRoute = ItemsItemIdImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact-form': {
      id: '/contact-form'
      path: '/contact-form'
      fullPath: '/contact-form'
      preLoaderRoute: typeof ContactFormImport
      parentRoute: typeof rootRoute
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-form': typeof ContactFormRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-form': typeof ContactFormRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact-form': typeof ContactFormRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact-form' | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact-form' | '/items/$itemId'
  id: '__root__' | '/' | '/contact-form' | '/items/$itemId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactFormRoute: typeof ContactFormRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactFormRoute: ContactFormRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact-form",
        "/items/$itemId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact-form": {
      "filePath": "contact-form.tsx"
    },
    "/items/$itemId": {
      "filePath": "items/$itemId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
